---
- name: upgrade all packages
  yum: name=* state=latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install additional system packages.
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ system_packages }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: "Update /etc/hosts file IPv4"
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{item}}" state=present
  with_items: "{{ host_names }}"

- name: "Update /etc/hosts file IPv6"
  lineinfile: dest=/etc/hosts line="::1 {{item}}" state=present
  with_items: "{{ host_names }}"

- pip:
    name: urllib3

- name: "PHP symlinks"
  file:
    src: "/opt/remi/php71/root/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items:
    - php
    - php-cgi
    - php-config
    - phpize
    - phar